DELIMITER $$
CREATE FUNCTION distance_inference_basique( source VARCHAR(255), cible VARCHAR(255) )
RETURNS INT
    DETERMINISTIC
BEGIN
DECLARE COUNT1, COUNT2 INT;
DECLARE I, J, L INT;
DECLARE C CHAR(1);
 
## CAS ELEMENTAIRES 
IF SOURCE IS NULL or CIBLE IS NULL 
THEN RETURN NULL; 
END IF;
IF SOURCE = CIBLE THEN 
RETURN 0;
END IF;
 
## LES AUTRES CAS, MAINTENANT !
SET COUNT1 = 0;
SET COUNT2 = 0;
 
SET I = 1;
SET J = 1;
SET L = CHAR_LENGTH(SOURCE);
 
premiere_passe:WHILE I <= L DO
   SET C = SUBSTRING(SOURCE, I, 1);
   IF LOCATE(C, CIBLE, J) > 0 THEN
      SET COUNT1 = COUNT1 + 1 ;
      SET J = LOCATE(C, CIBLE, J) + 1 ;
   END IF;
   SET I = I + 1;
END WHILE;
 
IF COUNT1 = 0 THEN RETURN 0; END IF;
 
SET I = 1;
SET J = 1;
SET L = CHAR_LENGTH(CIBLE);
 
seconde_passe:WHILE I <= L DO 
   SET C = SUBSTRING(CIBLE, I, 1);
   IF LOCATE(C, SOURCE, J) > 0 THEN
      SET COUNT2 = COUNT2 + 1;
      SET J = LOCATE(C, SOURCE, J) + 1;
   END IF;
   SET I = I + 1;
END WHILE;
 
IF COUNT1 < COUNT2 THEN
   SET COUNT1 = COUNT2;
END IF;
 
RETURN COUNT1;
END$$
DELIMITER ;